### ISSUE TITLE
Small installation bugs

### ISSUE THREAD

**Issue by Sogl** [koala-framework/kwf-cms-backbone-demo#1]
Hi!

Tried to setup:
1. Error SQL-installation.

```
 setup script(s) failed:
:
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY'
```

But `app_people` table created successfully.
1. Error on build step:

```
Warning: file_put_contents(cache/simple/Y29uZmlnQXItc2VydmVyLnJlcGxhY2VWYXJzLnJlbW90ZUFkZH6e32263a4baab58ab19ae917f93166a6): failed to open stream: No such file or directory in C:\OpenServer\domains\kwf-cms-backbone-demo\vendor\koala-framework\koala-framework\Kwf\Cache\SimpleStatic.php on line 52

(and many others in this way)
```

That's because `cache\simple` folder doesn't exists.
Same with `cache\view` folder. 
1. 404 on main page. Is it normal?

In final I see 3 lastname links and on click same lastname without link. Right work? =)

**Comment by nsams** [comment]
all errors should be fixed now.

> In final I see 3 lastname links and on click same lastname without link. Right work? =)

yes, that's all this demo does...
