### ISSUE TITLE
Home error 404: add content to home with link to /people

### ISSUE THREAD

**Issue by Sogl** [koala-framework/kwf-cms-backbone-demo#2]
Hi!

After composer update:
![404](https://cloud.githubusercontent.com/assets/7556290/7854967/4ceeecee-0561-11e5-83f6-88f544aa14f5.JPG)

How to fix?

**Comment by mifreudenthaler** [comment]
can you try http://kwf-cms-backbone-demo/people?
If you still get the error, check if the kwf_pages table has any content.

**Comment by Sogl** [comment]
> can you try http://kwf-cms-backbone-demo/people?

Ok, it works. Thx!

Is it possible to build same app (mixing backbone and ExtJS) based on kwf-app-demo?
